---
title: "NextReaction Priority Queue Performance"
output:
  pdf_document: default
  html_notebook: default
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(ggplot2)
library(data.table)
library(ggpubr)
theme_set(theme_bw())

DATA.SEQ.STDPQ <- data.table(read.table("stdpq-seqedges-benchmark.txt", header=TRUE))
DATA.SEQ.EXTPQ <- data.table(read.table("extpq-seqedges-benchmark.txt", header=TRUE))
DATA.CONC.STDPQ <- data.table(read.table("stdpq-concedges-benchmark.txt", header=TRUE))
DATA.CONC.EXTPQ <- data.table(read.table("extpq-concedges-benchmark.txt", header=TRUE))
DATA <- rbind(cbind(DATA.SEQ.STDPQ, queue="std (seq)"),
              cbind(DATA.SEQ.EXTPQ, queue="ext (seq)"),
              cbind(DATA.CONC.STDPQ, queue="std (conc)"),
              cbind(DATA.CONC.EXTPQ, queue="ext (conc)"))
```

## Total Runtimes

```{r echo=FALSE, message=FALSE, warning=FALSE}
knitr::kable(DATA[, list(`Runtime [s]`=signif(max(runtime), 3)), by=.(queue)])
```
## Queue Performance

```{r echo=FALSE, fig.height=8, fig.width=8, message=FALSE, warning=FALSE}
p <- ggarrange(
  ggplot(DATA) +
    geom_line(aes(x=step, y=infected, col=queue), alpha=0.8) +
    theme(legend.position="bottom"),
  ggplot(DATA) +
    geom_line(aes(x=step, y=active_edges, col=queue), alpha=0.8)+
    labs(y="active edges") +
    theme(legend.position="bottom"),
  ggplot(DATA) +
    geom_line(aes(x=step, y=us_per_qstep, col=queue), alpha=0.8) +
    scale_y_log10() +
    labs(y=expression(mu*"s / dequeue"))+
    theme(legend.position="bottom"),
  ncol=1, align="hv", heights=c(0.5, 0.5, 1.5), common.legend=TRUE
)
#d <- ggsave("pq-benchmark.plot.pdf", p, width=8, height=6)
p
```
